import { MailListElementData } from "@/components/mail/MailListElement";

export const mailListData: MailListElementData[] = [
  {
    mailID: 1,
    sender: "John Doe",
    from: "john.doe@example.com",
    to: "jane.smith@example.com",
    title: "Project Update",
    article:
      "Here is the latest update on the project. Please review and provide feedback.",
    files: ["report.pdf", "summary.xlsx"],
    isRead: true,
    isDownloaded: false,
    status: "sent",
    createdAt: new Date("2024-02-10T08:30:00Z"),
    modifiedAt: new Date("2024-02-11T10:15:00Z"),
  },
  {
    mailID: 2,
    sender: "Alice Wonderland",
    from: "alice.wonderland@example.com",
    to: "team@example.com",
    title: "Meeting Reminder",
    article: "Reminder: Team meeting scheduled for tomorrow at 10 AM.",
    files: [],
    isRead: false,
    isDownloaded: false,
    status: "received",
    createdAt: new Date("2024-02-12T14:45:00Z"),
    modifiedAt: new Date("2024-02-12T14:45:00Z"),
  },
  {
    mailID: 3,
    sender: "Support Team",
    from: "support@example.com",
    to: "user@example.com",
    title: "Account Verification",
    article: "Please verify your account by clicking the link below.",
    files: ["verification-link.txt"],
    isRead: true,
    isDownloaded: true,
    status: "received",
    createdAt: new Date("2024-02-13T09:00:00Z"),
    modifiedAt: new Date("2024-02-13T09:30:00Z"),
  },
  {
    mailID: 4,
    sender: "HR Department",
    from: "hr@example.com",
    to: "candidate@example.com",
    title: "Interview Schedule",
    article: "We would like to schedule an interview with you next week.",
    files: ["schedule.pdf"],
    isRead: false,
    isDownloaded: false,
    status: "received",
    createdAt: new Date("2024-02-14T11:20:00Z"),
    modifiedAt: new Date("2024-02-14T11:20:00Z"),
  },
];
